---
title: "Project Work"
author: "Cheyanne"
date: "5/6/2021"
output: html_document
---

```{r}
RacismData<-read.csv("C:\\Users\\buhl5\\Documents\\StatData.csv")
library(glmm)
library(MASS)
set.seed(42069)
```

```{r}
names(RacismData)
RacismData$contact<- factor(RacismData$contact)
RacismData$Minneapolis<- factor(RacismData$Minneapolis)
RacismData$RacialGroup<- factor(RacismData$RacialGroup, levels = c("White American", "Somali American", "African American"))
RacismData$Type<- factor(RacismData$Type)
RacismData$Sex<- factor(RacismData$Sex)
RacismData$Law<- factor(RacismData$Law)
RacismData$batch <- factor(RacismData$batch)

levels(RacismData$contact)<-c("Ambiguous","Ghosted","Negative","Positive")
```

To do:
1. Fit one model 
2. Perform one HT
3. Perform & interpret one CI

Data Exploration
```{r}
with(RacismData,plot(factor(RacismData$Minneapolis),factor(RacismData$contact)))
with(RacismData,plot(factor(RacismData$RacialGroup),factor(RacismData$contact)))
plot(RacismData$contact)
summary(RacismData$contact)
```

Model 1: Does Race Impact the log odds of receiving a positive response
```{r}
#response<- cbind(RacismData$Positive, 1-RacismData$Positive)
MPLS <- subset(RacismData, Minneapolis == "Minneapolis" & Size == "Two or more bedrooms")
rand <- sample(1:2432,500, replace = FALSE)
short <- MPLS[rand,]
GMM<- glmm(Positive~1, random = list(~0+batch),varcomps.names = c("batch"), m=1000, family.glmm = binomial.glmm(), data = short)
logLik(GMM)
summary(GMM)
```

Model: RacialGroup
```{r}
Sys.time()
RGMod<- glmm(Positive~RacialGroup, random = list(~0+batch),varcomps.names = c("batch"), m=1000, family.glmm = binomial.glmm(), data = short)
Sys.time()
logLik(RGMod)
summary(RGMod)
```

Model: Law
```{r}
Sys.time()
LMod<- glmm(Positive~Law*RacialGroup, random = list(~0+batch),varcomps.names = c("batch"), m=1000, family.glmm = binomial.glmm(), data = short)
Sys.time()
logLik(LMod)
summary(LMod)
```


Model 2: Bestest model :)
```{r}
mcse(LMod)
#summary(short$RacialGroup)
```

```{r}
mcse(RGMod)
```

```{r}
mcse(GMM)
```

```{r}
head(short)
```



